### ISSUE TITLE
Implement searching endpoint

### ISSUE THREAD

**Issue by yuna878** [cuappdev/coursegrab-backend#18]
Every time a user types a character to search, iOS sends a request to backend to get all matching results (similar to Transit search).

Return object format:
```
{
    "course_num": Int
    "subject_code": String
    "sections": [Section]
    "title": String
}
```
NOTE: `sections` are all sections that share the same `course_num`, `subject_code`, and `title`

**Comment by meganle** [comment]
323d9df2e161b8a2b0235f736b678df2cafa6fe8
