### ISSUE TITLE
Split Course and Sections

### ISSUE THREAD

**Issue by yuna878** [cuappdev/coursegrab-backend#19]
Make two db models:
Courses : has multiple sections
``` 
{ 
  course_title : "Intro to Backend", 
  course_number : "1998", 
  course_department : "CS"
}
```

Sections : belongs to one course
```
{
  type : LEC or DIS
  section_number : 201
  class_id : 12345
}
```

Update db schema / querying / scraper to reflect new models

**Comment by meganle** [comment]
444688f41f546c0be731d86fdf0a6d3b5e2f4743
